athletics_league/urls.py
from django.urls import path
from . import views
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('clubs/', views.ClubListView.as_view(), name='clubs'),
    path('club/<int:pk>', views.ClubDetailView.as_view(), name='club-detail'),
    path('leagues/', views.LeagueListView.as_view(), name='leagues'),
    # path('rankings/', views.RankingsListView.as_view(), name='rankings'),
    path('rankings/', views.RankingsSearchView, name='rankings'),
    path('pbs/', views.PBSearchView, name='pbs'),
    path('league/<int:pk>', views.LeagueDetailView.as_view(), name='league-detail'),
    path('athletes/', views.AthleteListView.as_view(), name='athletes'),
    path('athlete/<uuid:pk>', views.AthleteDetailView.as_view(), name='athlete-detail'),
    path('venues/', views.VenueListView.as_view(), name='venues'),
    path('venues/<uuid:pk>', views.VenueDetailView.as_view(), name='venue-detail'),
    path('seasons/', views.SeasonListView.as_view(), name='seasons'),
    path('seasons/<uuid:pk>', views.SeasonDetailView.as_view(), name='season-detail'),
    path('events/', views.EventListView.as_view(), name='events'),
    # Adding Urls
    # path('practice/', views.practice, name='practice'),
    path('AllParticipant/<uuid:pk>/', views.ListParticipant, name='AllParticipant'),
    path('addEvent/', views.AddEvent, name='addEvent'),
    path('AllEventResults/<uuid:pk>/', views.EventResult, name='AllResult'),
    path('AddResult/', views.AddRessult, name='AddResult'),
    path('AddResult/UpdateResult/<uuid:pk>', views.updateResult.as_view(), name='UpdateResult'),
    path('AthletePB/', views.Athletpb, name='athletePB'),
    path('AddPB/', views.AddPB.as_view(), name='addPB'),
    path('updatePB/<uuid:pk>', views.updatePB.as_view(), name='updatePB'),

    path('events/<uuid:pk>', views.EventDetailView, name='event-detail'),
    path('meetings/<uuid:pk>', views.MeetingDetailView.as_view(), name='meeting-detail'),
    path('seasonsRanking/', views.SeasonsRankingView.as_view(), name='seasonsRanking'),
    path('recalc_rankings/<uuid:pk>', views.recalc_rankings, name='recalc_rankings'),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

athletics_leagues/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from athletics_league import views

urlpatterns = [
    path('admin/', admin.site.urls),
]
from django.urls import include
urlpatterns += [
    path('athletics_league/', include('athletics_league.urls')),

]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='athletics_league/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#urlpatterns += [
#    path('RankingsSearchView/', views.),
#]


urlpatterns += [
    url(r'^search/$', views.search_ranking, name='search'),
]

athletics_league/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator 
# Create your models here.

class AgeGroup(models.Model):
    AgeGroup_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Age Grop across whole league')
    AgeGroup_name = models.CharField(max_length=20)
    AgeGroup_description = models.CharField(max_length=40)
    def __str__(self):
        return self.AgeGroup_name
    def get_absolute_url(self):
        """Returns the url to access a detail record for this athlete."""
        return reverse('agegroup-detail', args=[str(self.AgeGroup_ID)])


class Coach(models.Model):
    Coach_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Coach across whole league')
    Coach_name = models.CharField(max_length=20)
    Coach_surname = models.CharField(max_length=20)
    def __str__(self):
        return self.Coach_name + ' ' + self.Coach_surname

class Gender(models.Model):
    Gender_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Gender')
    GENDER_TYPE= (
        ('M', 'Male'),
        ('F', 'Felmale'),
    )
    """possible gender options"""
    gender= models.CharField(
        max_length=1000000,
        choices=GENDER_TYPE,
        blank=True,
        default='M',
        help_text='Athlete Gender',
    )

    def __str__(self):
        return self.gender
    

class Athlete(models.Model):
    """what consists of"""
    Athlete_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Athlete across whole league')
    Club = models.ForeignKey('Club', on_delete=models.SET_NULL, null=True)
    AgeGroup = models.ForeignKey('AgeGroup', on_delete=models.SET_NULL, null=True)
    Coach = models.ForeignKey('Coach', on_delete=models.SET_NULL, null=True)
    Athlete_Name = models.CharField(max_length=20)
    Athlete_Surname = models.CharField(max_length=20)
    Athlete_email = models.EmailField
    Date_of_birth = models.DateField(null=True, blank=True)
    Athlete_Gender = models.ForeignKey('Gender', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """ athlete full name"""
        return self.Athlete_Name + self.Athlete_Surname

    def get_absolute_url(self):
        """Returns the url to access a detail record for this athlete."""
        return reverse('athlete-detail', args=[str(self.Athlete_ID)])

class AthletePB(models.Model):
    AthletePB_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Personal Best')
    Speciality = models.ForeignKey('Speciality', on_delete=models.SET_NULL, null=True) 
    Athlete = models.ForeignKey('Athlete', on_delete=models.SET_NULL, null=True)
    Season = models.ForeignKey('Season', on_delete=models.SET_NULL, null=True)
    AgeGroup = models.ForeignKey('AgeGroup', on_delete=models.SET_NULL, null=True)
    Gender = models.ForeignKey('Gender', on_delete=models.SET_NULL, null=True)
    Speciality_Type = models.ForeignKey('SpecialityType', on_delete=models.SET_NULL, null=True)
    PB_Date = models.DateField(null=True, blank=True)
    pb_time = models.DurationField(null=True, blank=True)
    PB = models.ForeignKey('TrackEventResult', on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.PB_Date , self.pb_time , self.PB 

class Speciality(models.Model):
    Speciality_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Speciality across whole league')
    speciality_name = models.CharField(max_length=50)
    Speciality_Type = models.ForeignKey('SpecialityType', on_delete=models.SET_NULL, null=True)
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['speciality_name'], name='unique speciality name'),
        ]

    def __str__(self):
        return self.speciality_name

class SpecialityType(models.Model):
    SpecialityType_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Speciality across whole league')
    speciality_type = (
        ('T', 'Track'),
        ('F', 'Field'),
    )
    Speciality_type = models.CharField(
        max_length=10000,
        choices=speciality_type,
        blank=True,
        default='T',
        help_text='speciality type',
    )

    def __str__(self):
        return self.Speciality_type

class AthleteRanking(models.Model):
    AthleteRanking_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Athlete Ranking across whole league')
    Athlete = models.ForeignKey('Athlete', on_delete=models.SET_NULL, null=True)
    Speciality = models.ForeignKey('Speciality', on_delete=models.SET_NULL, null=True)
    Season = models.ForeignKey('Season', on_delete=models.SET_NULL, null=True)
    ranking = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1)],null=True, blank=True)
    AgeGroup = models.ForeignKey('AgeGroup', on_delete=models.SET_NULL, null=True)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['Athlete', 'Speciality', 'Season'], name='unique ranking per speciality per season'),
        ]

class Club(models.Model):
    """Club_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Club across whole league')"""
    League = models.ForeignKey('League', on_delete=models.SET_NULL, null=True)
    Club_Name = models.CharField(max_length=40)

    def __str__(self):
        """club name"""
        return self.Club_Name
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this club."""
        return reverse('club-detail', args=[str(self.id)])

class League(models.Model):
    League_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular league')
    League_Name = models.CharField(max_length=40)

    def __str__(self):
        return self.League_Name

class Meeting(models.Model):
    meeting_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular meet')
    League = models.ForeignKey('League', on_delete=models.SET_NULL, null=True)
    Season = models.ForeignKey('Season', on_delete=models.SET_NULL, null=True)
    meeting_name = models.CharField(max_length=40)
    meeting_date = models.DateField(null=True, blank=True)


    def __str__(self):
        return self.meeting_name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this athlete."""
        return reverse('meeting-detail', args=[str(self.meeting_ID)])

class Venue(models.Model):
    Venue_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular Venue')
    Venue_name = models.CharField(max_length=40)
    Venue_location = models.CharField(max_length=40)

    def __str__(self):
        return self.Venue_name
    
    COMP_COUNTY = (
        ('Su', 'Surrey'),
        ('We', 'Wessex'),
        ('Sus', 'Sussex'),
        ('Ke', 'Kent'),
        ('Es','Essex')
    )

    status = models.CharField(
        max_length=10000000,
        choices=COMP_COUNTY,
        blank=True,
        default='Su',
        help_text='county',
    )

def get_absolute_url(self):
        """Returns the url to access a detail record for this athlete."""
        return reverse('venue-detail', args=[str(self.Venue_ID)])
    
class Event(models.Model):
    event_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular event')
    Meeting = models.ForeignKey('Meeting', on_delete=models.SET_NULL, null=True)
    Speciality = models.ForeignKey('Speciality', on_delete=models.SET_NULL, null=True);
    round_type = models.ForeignKey('EventRound', on_delete=models.SET_NULL, null=True);
    event_name = models.CharField(max_length=40, null=True, blank=True)
    event_time = models.TimeField(null=True, blank=True)
    
    def __str__(self):
        return self.Meeting.meeting_name + ' - ' + self.Speciality.speciality_name + ' - ' + self.event_name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this event."""
        return reverse('event-detail', args=[str(self.event_ID)])

class EventRound(models.Model):
    eventRound_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular event round')
    round_type = (
        ('Heat', 'Heat'),
        ('Semi-final', 'Semi-final'),
        ('Final', 'Final')
    )

    event_round = models.CharField(
        max_length=10000000,
        choices=round_type,
        blank=True,
        default='Heat',
        help_text='Round Type',

    )

    def __str__(self):
        return self.event_round

class EventParticipant(models.Model):
    eventParticipant_ID = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular event participant')
    Event = models.ForeignKey('Event', on_delete=models.SET_NULL, null=True)
    Athlete = models.ForeignKey('Athlete', on_delete=models.SET_NULL, null=True)
    bib = models.CharField(max_length=3)
    lane = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1), MaxValueValidator(100)],null=True, blank=True)
   
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['Event', 'Athlete'], name='unique athlete for event'),
            models.UniqueConstraint(fields=['Event','bib'], name='unique bib for event')
        ]

    def __str__(self):
        return self.Event.Meeting.meeting_name + ' - ' + self.Event.Speciality.speciality_name + ' - ' + str(self.lane) + ' - ' + self.Athlete.Athlete_Surname + ' - ' + self.bib

    def get_absolute_url(self):

athletics_league/forms.py
from django import forms
from .models import EventParticipant,TrackEventResult,AthletePB


class EventParticipantModel(forms.ModelForm):
    
    class Meta:
        model = EventParticipant
        fields = ['Event','Athlete','bib','lane']

class EventTrackModel(forms.ModelForm):
    
    class Meta:
        model = TrackEventResult 
        fields = ['EventParticipant','duration']

class AthletePBModel(forms.ModelForm):
    
    class Meta:
        model = AthletePB
        fields = ['Speciality','Athlete','Season','AgeGroup','Gender','Speciality_Type','PB_Date','pb_time','PB']

athletics_league/templates/athletics_league/Addathlete_pb.html
<h1>Add Athlete</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Add</button>
</form>

athletics_league/templates/athletics_league/AllParticipant.html
  
<h1> Event Participants</h1>
{{event_obj.Event}} <br>
{% for i in event_obj  %} 
<h4>Event Name : {{i.Event}}</h4>
  <strong> Name:</strong> {{i.Athlete}} <br>   
   <strong> Bib:</strong>{{i.bib}}   <br>
  <strong> Lane:</strong>{{i.lane}}   <hr>
      



    {% endfor %}
  </table>
    
        

athletics_league/templates/athletics_league/AllResults.html
{% extends "base_generic.html" %}

{% block content %}


<h1>Added Results</h1>
<br>
{% for i in eventresult  %}

<ul>
    <li> <h2> Event Participant:</h2> {{i.EventParticipant}} <br>
    <li> <h2> Athlete:</h2> {{i.EventParticipant.Athlete}} <br>
        <h2>Duration: </h2> {{i.duration}}        
        -- 
        {% if user.is_superuser %}
<button class="btn btn-primary-sm">  <a class="btn btn-primary-sm" href="{% url 'UpdateResult' i.pk %}">Edit</a></button> 
                
        {% endif %}

    <hr>
    </li>
    
</ul> 
{% endfor %}

{% endblock %}

athletics_league/templates/athletics_league/Event_Result_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ meeting.meeting_name }}</h1>
  <p><strong>Events for this Meet:</strong> <a href="">{{ Meeting.event }}</a></p> 
  {% for event in meeting.event_set.all|dictsort:"event_time" %}
      <hr>
      <p><strong>Event :</strong> <a href="{{ event.get_absolute_url }}">{{ event.event_name }}</a></p> 
  {% endfor %}
  
  

{% endblock %}

athletics_league/templates/athletics_league/addEvent.html
<h1>Add Event Participant</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{Form.as_p}}
    

    <button type="submit">Submit</button>
</form>

athletics_league/templates/athletics_league/athlete_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ athlete.Athlete_Name }}</h1>

  <p><strong>Club:</strong> <a href="">{{ athlete.Club }}</a></p> <!-- author detail link not yet defined -->
  
  <p><strong>Rankings  for this Athlete:</strong></p>
  {% for athleteranking in athlete.athleteranking_set.all%}
      <hr>
      <p><strong>Ranking :</strong> {{ athleteranking.Season.season_Name }} -- {{ athleteranking.Speciality.speciality_name }} ---> {{athleteranking.ranking}}</a></p> 
  {% endfor %}
  
  
  
{% endblock %}

athletics_league/templates/athletics_league/athleteranking_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Rankings Search</h1>
  <form method="get">
    {{ filter.form }}
    <button type="submit">Search</button>
  </form>
  <ul>
    {%for athleteranking in rankings%}
    <p><a href="{{ athleteranking.Athlete.get_absolute_url }}">{{ athleteranking.Athlete }}</a> </p>
    {% endfor %}
  </ul>
  <!-- 
  {% if event_list %}
  <ul>
    {% for event in event_list %}
      <li>
        <a href="{{ event.get_absolute_url }}">{{ event.Event_Name}}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no events.</p>
  {% endif %}
-->  
{% endblock %}

athletics_league/templates/athletics_league/event_detail.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
<style>
  table, th, td {
    border: 2px solid black;
    border-collapse: collapse;
    padding: 10%;
  }
</style>
<h1>{{ event.event_name }}</h1>
{% if event.status == "T" %}
<ul>
  <p><strong>This is a track event</strong></p>
</ul>
{% else %}
<p>This is a field event</p>
{% endif %}

<ul>
  <p><strong>Event results for this event:</strong></p>
<h1>The Successors of All the HEAT:</h1>

<br>
{% for i in Participant|slice:'1'  %}
<b>
{% for j in i.trackeventresult_set.all|dictsort:'duration'|slice:'2' %}
  
{{j.EventParticipant}} <br>
{{j.duration}}
<hr>
{% endfor %}
<!-- Event: {{i.Event}}
Speciality: {{i.Event.Speciality}} <br>
Round: {{i.Event.round_type}} <br>
Duration: {{j.duration}} -->

</b>


{% endfor %}
  <br><br>

{{finalist.bib}}
<br>
{% if user.is_superuser %}
<h2 class="alert alert-warning">More Options:</h2>

  <button class="btn btn-primary"> <a  class="btn btn-primary" href="{% url 'AddResult' %}">Add Resutl</a></button>   
  <button class="btn btn-primary" > <a class="btn btn-primary" href="{% url 'addEvent' %}">Add Participant</a></button> 
  <button class="btn btn-primary"> <a class="btn btn-primary"  href="{% url 'addPB' %}">  Add Athlete</a> </button>
 
  {% endif %}
    

<br><br>


    <br>
    <!-- <p><a href="{{ eventparticipant.Athlete.get_absolute_url }}">{{ eventparticipant.Athlete }}</a> {{eventparticipant.bib}} {{eventparticipant.lane}}</p> -->
  


    <hr>

</ul>

<p>There are no results yet</p>

{% endblock %}

athletics_league/templates/athletics_league/event_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Event List </h1>
  {% if event_list %}
  <ul>
    {% for event in event_list %}
      <li>
        <a href="{{ event.get_absolute_url }}">{{ event.Event_Name}}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no events.</p>
  {% endif %}       
{% endblock %}

athletics_league/templates/athletics_league/meeting_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ meeting.meeting_name }}</h1>
  <p><strong>Events for this Meet: </strong> <a href="">{{ Meeting.event }}</a></p> 
  {% for event in meeting.event_set.all|dictsort:"event_time" %}
      <hr>
	  <p><strong>Event :</strong> <a href="{{ event.get_absolute_url }}">{{ event.event_name }}</a></p>
  {% endfor %}
  
  

{% endblock %}

athletics_league/templates/athletics_league/season_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ season.season_Name }}</h1>
  <p><strong>Meetings for this season:</strong> <a href="">{{ club.Meeting }}</a></p> 
  {% for meeting in season.meeting_set.all|dictsort:"meeting_date" %}
      <hr>
      <p><strong>Meeting :</strong> <a href="{{ meeting.get_absolute_url }}">{{ meeting.meeting_name }}</a>,  {{meeting.meeting_date}}</p> 
  {% endfor %}
  

{% endblock %}

athletics_league/templates/athletics_league/season_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Season List</h1>
  {% if season_list %}
  <ul>
    {% for season in season_list %}
      <li>
        <a href="{{ season.get_absolute_url }}">{{ season.season_Name}}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Season.</p>
  {% endif %}       
{% endblock %}

athletics_league/templates/athletics_league/updateEvent.html
<h1>Edit Event</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Edit</button>
</form>

athletics_league/templates/athletics_league/updateResult.html
<h1>Update Result</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update</button>
</form>